
GET http://localhost:8080/carrito HTTP/1.1
###
POST http://localhost:8080/carrito HTTP/1.1
content-type: application/json

{
    "email": "uno@gmail.com",
    "direccionentrega": "direccion111",
    "items": [{
    "idproducto": "63b9feb1f790136cc7464901",
    "descripcion": "manzana",
    "cantidad": 20
    }]
}
###
PUT http://localhost:8080/carrito/63bae2ecf5c5a986ea8db909 HTTP/1.1
content-type: application/json

{
    "direccionentrega": "direccion222"
}
###
DELETE http://localhost:8080/carrito/63bae2ecf5c5a986ea8db909 HTTP/1.1
############
# items carrito
############
DELETE http://localhost:8080/carrito/63bae40d9b2428395683cfbe/63b9feb1f790136cc7464901 HTTP/1.1


