#GET http://localhost:8080/api/carrito HTTP/1.1

# POST http://localhost:8080/api/carrito HTTP/1.1
# content-type: application/json

# {
#     "productos": [{
#     "id": 1,
#     "timestamp": "1661351850769", 
#     "nombre": "Manzana",
#     "descripcion": "Manzanas", 
#     "codigo": "MZ1", 
#     "foto": "https://media.istockphoto.com/photos/red-apple-picture-id184276818?k=20&m=184276818&s=612x612&w=0&h=QxOcueqAUVTdiJ7DVoCu-BkNCIuwliPEgtAQhgvBA_g=", 
#     "precio": 12, 
#     "stock": 100
# },
# {
#     "id": 2,
#     "timestamp": "", 
#     "nombre": "Manzana",
#     "descripcion": "Manzanas", 
#     "codigo": "MZ1", 
#     "foto": "https://media.istockphoto.com/photos/red-apple-picture-id184276818?k=20&m=184276818&s=612x612&w=0&h=QxOcueqAUVTdiJ7DVoCu-BkNCIuwliPEgtAQhgvBA_g=", 
#     "precio": 12, 
#     "stock": 100
# }]
# }

# PUT http://localhost:8080/api/carrito/2 HTTP/1.1
# content-type: application/json

#  {
#     "timestamp": 1661352057233,
#      "productos": [
#       {
#         "id": 1,
#         "timestamp": "1661351850769",
#         "nombre": "Manzana",
#         "descripcion": "Manzanas",
#         "codigo": "MZ1",
#         "foto": "https://media.istockphoto.com/photos/red-apple-picture-id184276818?k=20&m=184276818&s=612x612&w=0&h=QxOcueqAUVTdiJ7DVoCu-BkNCIuwliPEgtAQhgvBA_g=",
#         "precio": 12,
#         "stock": 100
#       },
#       {
#         "id": 2,
#         "timestamp": "",
#         "nombre": "Manzana",
#         "descripcion": "Manzanas",
#         "codigo": "MZ1",
#         "foto": "https://media.istockphoto.com/photos/red-apple-picture-id184276818?k=20&m=184276818&s=612x612&w=0&h=QxOcueqAUVTdiJ7DVoCu-BkNCIuwliPEgtAQhgvBA_g=",
#         "precio": 12,
#         "stock": 100
#       }
#     ]
# }

#DELETE http://localhost:8080/api/carrito/1 HTTP/1.1

# DELETE http://localhost:8080/api/carrito/2/productos/2 HTTP/1.1

