
GET http://localhost:8080/carrito HTTP/1.1
###
POST http://localhost:8080/carrito HTTP/1.1
content-type: application/json

{
    "email": "uno@gmail.com",
    "direccionengrega": "direccion",
    "items": [{
    "idproducto": "1",
    "descripcion": "manzana",
    "cantidad": 10
    }]
}
###
PUT http://localhost:8080/carrito/1 HTTP/1.1
content-type: application/json

{
    "email": "uno@gmail.com",
    "direccionengrega": "direccion12",
    "items": [{
    "idproducto": "1",
    "descripcion": "manzana",
    "cantidad": 10
    }]
}
###
DELETE http://localhost:8080/carrito/1 HTTP/1.1


