
GET http://localhost:8080/ordenes HTTP/1.1
###
POST http://localhost:8080/ordenes HTTP/1.1
content-type: application/json

{
    "email": "tres@gmail.com",
    "estado": "generada",
    "items": [{
    "idproducto": "63b9feb1f790136cc7464901",
    "descripcion": "manzana",
    "cantidad": 20,
    "precio": 10
    }]
}
###
PUT http://localhost:8080/ordenes/63bae76f0e158b6774232b9f HTTP/1.1
content-type: application/json

{
    "email": "dos@gmail.com"
}
###
DELETE http://localhost:8080/ordenes/63bae7140e158b6774232b99 HTTP/1.1


